### ISSUE TITLE
PH and PRS status "unknown"

### ISSUE THREAD

**Issue by Obelix3000** [zachi40/home-assistant-mycodo#1]
Hi, 
very hapy to finally have a HA integration for Mycodo. I have built a vertical farm controlled by a Mycodo-Armee. So putting everything up with yaml was intense work. Thank you for your work!!!

So i installed your integration, and it works great, but pH and pressure sensor status shows up as "unknown". I hav this problem with every Mycodo Unit. But directly in Mycodo, i have values.

````

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.mycodo_app.sensor
Quelle: custom_components/mycodo_app/sensor.py:131
Integration: MyCodo App (Dokumentation, Probleme)
Erstmals aufgetreten: 13:44:07 (165 Vorkommnisse)
Zuletzt protokolliert: 14:24:37

No data found for sensor 'Mycodo Mizuna PRS' with ID 5ba8af9f-9a29-46d1-8d94-49289a51b337
No data found for sensor 'Mycodo Mizuna PH' with ID 96ed6a25-14f5-4fa3-b795-d5d418171e33
No data found for sensor 'Mycodo Ping' with ID ce32de74-f72d-4313-8f5e-604821449b6f
No data found for sensor 'Mycodo Atlas Pressure' with ID 341f3f68-39b4-4432-94df-6a6d08dafc77
No data found for sensor 'Mycodo Atlas pH' with ID 848796b3-6a42-4944-b0c1-f8f91f85fe59`

```

**Comment by zachi40** [comment]
Issues [Fixed ](https://github.com/zachi40/home-assistant-mycodo/commit/d15b40d7479a397eb3e6e4fd24831e26de334913), Please update the plugin
