### ISSUE TITLE
Failed to update sensor 

### ISSUE THREAD

**Issue by Obelix3000** [zachi40/home-assistant-mycodo#4]
Hi again,
always when any Mycodo shuts off, or restarts, then the extension is loosing the connection and gets stuck in a loop or something. Restarting HA or the Mycodos is not solving the problem. It looks like the extension ist connecting to mycodo auf restart, but wants to add the same sensor again and gets "unique-ID-already in use" error.

Sure, when i reinstall the extension, then everything is back on top. 

`Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.mycodo_app.sensor
Quelle: custom_components/mycodo_app/sensor.py:169
Integration: MyCodo App (Dokumentation, Probleme)
Erstmals aufgetreten: 08:47:02 (332 Vorkommnisse)
Zuletzt protokolliert: 11:26:01

Failed to update sensor 'Mycodo Radish PRS pressure' with ID a25f34be-34da-45f3-bca8-8a57a127ae75
Failed to update sensor 'Mycodo Radish RTD temperature' with ID d1b856a5-3f1a-49ed-aca5-db61253bcc51
Failed to update sensor 'Mycodo Radish PH ion_concentration' with ID 86d61092-1652-465f-b5f0-415e8e0c0916`

![image](https://github.com/zachi40/home-assistant-mycodo/assets/109316553/fe4a34eb-b9ab-4613-a763-100d9989b07a)

**Comment by zachi40** [comment]
Please upload your HA logs, to watch the problem

**Comment by Obelix3000** [comment]
Hi, sry for the late response. 
[home-assistant_2024-07-16T07-49-12.864Z.log](https://github.com/user-attachments/files/16245022/home-assistant_2024-07-16T07-49-12.864Z.log)

Meanwhile i started thinking of that its because HA is messing upsomething or me. So i did a whole new HA installation and started from scratch, with same problems again. 

I have another Mycodo System in a different place which controlls a grow tent. Well, this one is running from day one without issues.

**Comment by zachi40** [comment]
I see a lot of errors in the log file, I'm not sure if it's due from my add-on, to be sure delete my add-on and see if the error returns. If so (and the errors are back) see where they come from, if not upload the log file again
