### ISSUE TITLE
Failing to switch outputs

### ISSUE THREAD

**Issue by m0edev** [zachi40/home-assistant-mycodo#5]
Everything's working but the switching of outputs

This error originated from a custom integration.

Logger: custom_components.mycodo_app.switch
Source: custom_components/mycodo_app/switch.py:92
integration: MyCodo App (documentation, issues)
First occurred: 3:48:50 PM (3 occurrences)
Last logged: 3:48:54 PM

Failed to turn on Mycodo Heater (6)
Failed to turn on Mycodo Humidifer (13)
Failed to turn on Mycodo Extract Fan (26)

**Comment by zachi40** [comment]
Please upload your HA logs, to watch your problem

**Comment by m0edev** [comment]
[home-assistant_2024-07-13T06-26-55.794Z.log](https://github.com/user-attachments/files/16201157/home-assistant_2024-07-13T06-26-55.794Z.log)
 
 Full log file attached

**Comment by zachi40** [comment]
Thank you for the logs. 
On the Mycodo Dashboard, do you see the data from the sensors "SCD30 dewpoint" and "SCD30 dewpoint"? 
According to the log you sent, it appears there is no information available form these sensors.

**Comment by m0edev** [comment]
I have disabled those in mycodo, I only recently just disabled them in HA as I do not use them. I use temp, humidity and c02 from mycodo.

The issue I'm facing is I'm not able to control my mycodo inputs from HA

**Comment by zachi40** [comment]
Try reinstalling , if the problem is still not resolved, upload the HA log with the error

**Comment by m0edev** [comment]
Reinstall fixed the issue, Thanks :) Love your work!
