### ISSUE TITLE
Feature Suggestion: add possibilty to add Function outputs

### ISSUE THREAD

**Issue by flo269** [zachi40/home-assistant-mycodo#6]
I calculate average temperature and humidity values using functions. Would it somehow be possible to also share the output of these functions with home assistant?

Thank you!

**Comment by zachi40** [comment]
I'm not sure if it's possible because the system doesn't show the result, only the code you wrote.
But to be sure, can you share the code of what you're running? I'll look maybe the system shows the result somewhere.

**Comment by flo269** [comment]
I'm using the stock "Average (Last, Multiple)" function. If you need any other info, please let me know. Thanks!!

![Screenshot 2024-11-10 at 11 22 26](https://github.com/user-attachments/assets/d00b1293-83fa-4203-b125-21ddc0ec29da)
![Screenshot 2024-11-10 at 11 22 38](https://github.com/user-attachments/assets/d6567979-3c41-4d0b-9043-946df425405c)

**Comment by zachi40** [comment]
Yes, it's like what I thought. It only shows the functions' settings and not the result.

![image](https://github.com/user-attachments/assets/5ff68a6d-f43f-4e8a-9e3f-8b095d673a9b)
![image](https://github.com/user-attachments/assets/f35d6b53-0642-4411-ac70-54021e18f1a0)

**Comment by flo269** [comment]
Aw, that's too bad. But thanks for checking it out! :-)

I probably just don't entirely understand, but when I look at this, it looks like it's supposed to return a measurement?

https://kizniche.github.io/Mycodo/mycodo-api.html#tag/functions/operation/get_settings_functions_unique_id
![Screenshot 2024-11-10 at 20 35 30](https://github.com/user-attachments/assets/9a22f9d0-4095-4e10-83ca-b9e483ce60a8)

**Comment by zachi40** [comment]
![image](https://github.com/user-attachments/assets/286dff72-bfb2-4777-b17e-9acd1d0ba8b5)
This is what appears under this option, I don't see the result of the function there.

**Comment by kizniche** [comment]
If you want a measurement, you can use the measurement API endpoints, e.g. https://kizniche.github.io/Mycodo/mycodo-api.html#tag/measurements/operation/get_measurements_last
